export default  [{
    1: [{
        "id": 1,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "07:30",
        "duracion": "07:30 - 08:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "08:15",
        "duracion": "08:15 - 09:05",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://elpais.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 4,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Step Tono",
        "estilo": "step-tono",
        "sala": "Sala 1",
        "enlace": "http://dagondesign.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 5,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "https://hatena.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 6,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newyorker.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 7,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "15:00",
        "duracion": "15:00 - 15:55",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://usgs.gov",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 8,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "15:30",
        "duracion": "15:30 - 16:25",
        "actividad": "L-Training",
        "estilo": "l-training",
        "sala": "Box",
        "enlace": "https://nbcnews.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 9,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://paypal.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 10,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "https://yandex.ru",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 11,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 12,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Body Concept",
        "estilo": "body-concept",
        "sala": "Sala 1",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 13,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Zumba",
        "estilo": "zumba",
        "sala": "Sala 2",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 14,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newsvine.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 15,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 16,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Sevillanas",
        "estilo": "sevillanas",
        "sala": "Sala 2",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 17,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Flamenco",
        "estilo": "flamenco",
        "sala": "Sala 2",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 18,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "Coreográfico Estilo Chicas",
        "estilo": "coreográfico",
        "sala": "Sala 2",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 19,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 20,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    },{
        "id": 21,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 22,
        "dia": 1,
        "hoy": "Lunes",
        "horaclase": "08:15",
        "duracion": "08:15 - 09:05",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }],
    2: [{
        "id": 1,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "07:30",
        "duracion": "07:30 - 08:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "08:30",
        "duracion": "08:30 - 09:25",
        "actividad": "TRX",
        "estilo": "trx",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://elpais.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 4,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Zumba",
        "estilo": "zumba",
        "sala": "Sala 2",
        "enlace": "http://dagondesign.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 5,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "https://hatena.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 6,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newyorker.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 7,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "15:30",
        "duracion": "15:30 - 16:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://usgs.gov",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 8,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "17:30",
        "duracion": "17:30 - 18:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://nbcnews.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 9,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "19:00",
        "duracion": "19:00 - 19:55",
        "actividad": "Cardio Fitness",
        "estilo": "cardio-fitness",
        "sala": "Sala 1",
        "enlace": "http://paypal.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 10,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "20:00",
        "duracion": "20:00 - 20:55",
        "actividad": "Gap Streching",
        "estilo": "gap",
        "sala": "Sala 1",
        "enlace": "https://yandex.ru",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 11,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 12,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 13,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Bachata Inicio",
        "estilo": "bachata-inicio",
        "sala": "Sala 2",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 14,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "21:00",
        "duracion": "21:00 - 22:55",
        "actividad": "Bachata Avanzado",
        "estilo": "bachata-avanzado",
        "sala": "Sala 2",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 15,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "Bachata Medio",
        "estilo": "bachata-medio",
        "sala": "Sala 2",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 16,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "17:30",
        "duracion": "17:30 - 18:25",
        "actividad": "Karate Niños 1",
        "estilo": "karate-ninos-1",
        "sala": "Sala 3",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 17,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "Karate Niños 2",
        "estilo": "karate-ninos-2",
        "sala": "Sala 3",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 18,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "20:00",
        "duracion": "20:00 - 20:55",
        "actividad": "Karate Adultos",
        "estilo": "karate-adultos",
        "sala": "Sala 3",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 19,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "21:00",
        "duracion": "21:00 - 22:55",
        "actividad": "Ninjutsu (Bujinkan)",
        "estilo": "ninjutsu",
        "sala": "Sala 3",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 20,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 21,
        "dia": 2,
        "hoy": "Martes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }],
    3: [{
        "id": 1,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "07:30",
        "duracion": "07:30 - 08:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "08:15",
        "duracion": "08:15 - 09:05",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://elpais.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 4,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Step Tono",
        "estilo": "step-tono",
        "enlace": "http://dagondesign.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 5,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://hatena.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 6,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "15:00",
        "duracion": "15:00 - 15:55",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newyorker.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 7,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "15:30",
        "duracion": "15:30 - 16:25",
        "actividad": "TRX",
        "estilo": "trx",
        "sala": "Sala 2",
        "enlace": "https://usgs.gov",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 8,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "18:00",
        "duracion": "18:00 - 18:55",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "https://nbcnews.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 9,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://paypal.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 10,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "TRX",
        "estilo": "trx",
        "sala": "Sala 2",
        "enlace": "https://yandex.ru",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 11,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "FitBall",
        "estilo": "fitball",
        "sala": "Box",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 12,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Step Tono",
        "estilo": "step-tono",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 13,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 14,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 15,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "17:30",
        "duracion": "17:30 - 18:25",
        "actividad": "Salsa Bachata Infantil",
        "estilo": "salsa-infantil",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 16,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "21:00",
        "duracion": "21:00 - 22:55",
        "actividad": "Bachata Medio",
        "estilo": "bachata-medio",
        "sala": "Sala 2",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 17,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "22:00",
        "duracion": "22:00 - 22:55",
        "actividad": "Bachata Inicio",
        "estilo": "bachata-inicio",
        "sala": "Sala 2",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 18,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 19,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 20,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "http://ocn.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 21,
        "dia": 3,
        "hoy": "Miércoles",
        "horaclase": "08:15",
        "duracion": "08:15 - 09:05",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }],
    4: [{
        "id": 1,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "07:30",
        "duracion": "07:30 - 08:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "08:30",
        "duracion": "08:30 - 09:25",
        "actividad": "Body Concept",
        "estilo": "body-concept",
        "sala": "Sala 1",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://elpais.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 4,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Body Concept",
        "estilo": "body-concept",
        "sala": "Sala 1",
        "enlace": "http://dagondesign.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 5,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "FitBall",
        "estilo": "fitball",
        "sala": "Box",
        "enlace": "https://hatena.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 6,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newyorker.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 7,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "15:30",
        "duracion": "15:30 - 16:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://usgs.gov",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 8,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "17:30",
        "duracion": "17:30 - 18:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://nbcnews.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 9,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "18:00",
        "duracion": "18:00 - 18:55",
        "actividad": "Boot Camp",
        "estilo": "boot-camp",
        "sala": "Box",
        "enlace": "http://paypal.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 10,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "19:00",
        "duracion": "19:00 - 19:55",
        "actividad": "Body Concept",
        "estilo": "body-concept",
        "sala": "Sala 1",
        "enlace": "https://yandex.ru",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 11,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "20:00",
        "duracion": "20:00 - 20:55",
        "actividad": "Zumba",
        "estilo": "zumba",
        "sala": "Sala 2",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 12,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://deliciousdays.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 13,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "21:30",
        "duracion": "21:30 - 22:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 14,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Salsa Inicio",
        "estilo": "salsa-inicio",
        "sala": "Sala 2",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 15,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "21:00",
        "duracion": "21:00 - 22:55",
        "actividad": "Salsa Medio",
        "estilo": "salsa-medio",
        "sala": "Sala 2",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 16,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "22:00",
        "duracion": "22:00 - 22:55",
        "actividad": "Salsa Inicio",
        "estilo": "salsa-inicio",
        "sala": "Sala 2",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 17,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "17:30",
        "duracion": "17:30 - 18:25",
        "actividad": "Step Tono",
        "estilo": "step-tono",
        "sala": "Sala 3",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 18,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "Karate Niños 2",
        "estilo": "karate-ninos-2",
        "sala": "Sala 3",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 19,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "21:00",
        "duracion": "21:00 - 22:55",
        "actividad": "Karate Adultos",
        "estilo": "karate-adultos",
        "sala": "Sala 3",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 20,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "22:00",
        "duracion": "22:00 - 22:55",
        "actividad": "Ninjutsu (Bujinkan)",
        "estilo": "ninjutsu",
        "sala": "Sala 3",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 21,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 22,
        "dia": 4,
        "hoy": "Jueves",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "Box Noray",
        "estilo": "box-noray",
        "sala": "Box",
        "enlace": "https://ted.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }],
    5: [{
        "id": 1,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "07:30",
        "duracion": "07:30 - 08:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "08:30",
        "duracion": "08:30 - 09:25",
        "actividad": "TRX",
        "estilo": "trx",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://elpais.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 4,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "http://dagondesign.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 5,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "09:30",
        "duracion": "09:30 - 10:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://hatena.ne.jp",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 6,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "15:00",
        "duracion": "15:00 - 15:55",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://newyorker.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 7,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "15:30",
        "duracion": "15:30 - 16:25",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "https://usgs.gov",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 8,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "18:15",
        "duracion": "18:15 - 19:05",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "https://nbcnews.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 9,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://paypal.com",
        "imagen": "http://dummyimage.com/200x40.png/ff4444/ffffff"
    }, {
        "id": 10,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "19:00",
        "duracion": "19:00 - 19:55",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://yandex.ru",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 11,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "20:30",
        "duracion": "20:30 - 21:25",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 12,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "18:30",
        "duracion": "18:30 - 19:25",
        "actividad": "Baile Moderno Infantil",
        "estilo": "baile-moderno",
        "sala": "Sala 2",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }, {
        "id": 13,
        "dia": 5,
        "hoy": "Viernes",
        "horaclase": "19:30",
        "duracion": "19:30 - 20:25",
        "actividad": "Ladies Noray Inicio",
        "estilo": "ladies",
        "sala": "Sala 2",
        "enlace": "http://weather.com",
        "imagen": "http://dummyimage.com/200x40.png/dddddd/000000"
    }],
    6: [{
        "id": 1,
        "dia": 6,
        "hoy": "Sábado",
        "horaclase": "10:15",
        "duracion": "10:15 - 11:05",
        "actividad": "SpinBike Virtual",
        "estilo": "spinbike",
        "sala": "Sala 1",
        "enlace": "https://weebly.com",
        "imagen": "http://dummyimage.com/200x40.png/5fa2dd/ffffff"
    }, {
        "id": 2,
        "dia": 6,
        "hoy": "Sábado",
        "horaclase": "19:00",
        "duracion": "19:00 - 19:55",
        "actividad": "Yoga",
        "estilo": "yoga",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }, {
        "id": 3,
        "dia": 6,
        "hoy": "Sábado",
        "horaclase": "19:00",
        "duracion": "19:00 - 19:55",
        "actividad": "Pilates",
        "estilo": "pilates",
        "sala": "Sala 2",
        "enlace": "http://altervista.org",
        "imagen": "http://dummyimage.com/200x40.png/cc0000/ffffff"
    }]
}]

